import { DataSource } from 'typeorm';
import { Category } from './entities/Category';
import { Item } from './entities/Item';

export async function seedDatabase(dataSource: DataSource): Promise<void> {
  const categoryRepo = dataSource.getRepository(Category);
  const itemRepo = dataSource.getRepository(Item);

  const existingCategories = await categoryRepo.count();
  if (existingCategories > 0) {
    return; // Already seeded
  }

  // Create Categories
  const categories = await categoryRepo.save([
    {
      name: 'Restaurants',
      slug: 'restaurants',
      description: 'Fine dining and culinary experiences curated for the discerning palate.',
      icon: '🍽️',
      sortOrder: 1,
    },
    {
      name: 'High-End Audio',
      slug: 'high-end-audio',
      description: 'Reference-grade headphones, DACs, amplifiers and speakers for audiophiles.',
      icon: '🎧',
      sortOrder: 2,
    },
    {
      name: 'Luxury Watches',
      slug: 'luxury-watches',
      description: 'Exceptional timepieces from the world\'s most prestigious watchmakers.',
      icon: '⌚',
      sortOrder: 3,
    },
    {
      name: 'Curated Tech',
      slug: 'curated-tech',
      description: 'Premium gadgets and accessories that blend form and function.',
      icon: '💻',
      sortOrder: 4,
    },
    {
      name: 'Fine Spirits',
      slug: 'fine-spirits',
      description: 'Exceptional whiskies, wines, and craft cocktails for the connoisseur.',
      icon: '🥃',
      sortOrder: 5,
    },
  ]);

  const [restaurants, audio, watches, tech, spirits] = categories;

  // Seed Restaurants
  await itemRepo.save([
    {
      title: 'Eleven Madison Park',
      slug: 'eleven-madison-park',
      description: 'Three-Michelin-star restaurant offering an innovative plant-based tasting menu in an iconic Art Deco dining room.',
      longDescription: 'Eleven Madison Park, helmed by Chef Daniel Humm, has long been considered one of the world\'s greatest restaurants. The dining room occupies a grand Art Deco space in the Metropolitan Life Insurance Company Tower, with soaring ceilings and floor-to-ceiling windows. The tasting menu is a meditation on plant-based cuisine, reimagining vegetables and grains with the same reverence previously reserved for luxury proteins. Each course is a study in restraint and technique, with dishes that surprise and delight. The wine program, curated by sommelier Cedric Nicaise, is encyclopedic and expertly paired.',
      imageUrl: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
      rating: 4.9,
      priceRange: '$$$$',
      category: restaurants,
      tags: JSON.stringify(['fine dining', 'plant-based', 'tasting menu', 'new york', 'michelin star']),
      featured: true,
    },
    {
      title: 'Noma Copenhagen',
      slug: 'noma-copenhagen',
      description: 'Legendary New Nordic restaurant by René Redzepi, pioneering fermentation and foraged ingredients.',
      longDescription: 'Noma has repeatedly been named the world\'s best restaurant, and its influence on global cuisine is immeasurable. Chef René Redzepi\'s kitchen has defined the New Nordic movement, celebrating local, seasonal, and foraged ingredients with extraordinary creativity. The restaurant operates on a seasonal menu concept, shifting its focus to seafood, vegetables, and game & forest at different times of year. The setting on Copenhagen\'s waterfront is rustic yet refined. Dining here is less a meal than a cultural expedition.',
      imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800',
      rating: 4.8,
      priceRange: '$$$$',
      category: restaurants,
      tags: JSON.stringify(['new nordic', 'fermentation', 'foraged', 'copenhagen', 'michelin star']),
      featured: true,
    },
    {
      title: 'Sukiyabashi Jiro',
      slug: 'sukiyabashi-jiro',
      description: 'The legendary 10-seat sushi counter in Tokyo where master Jiro Ono has perfected nigiri for over seven decades.',
      longDescription: 'To dine at Sukiyabashi Jiro is to witness a lifetime of dedication translated into each piece of nigiri. Jiro Ono, now in his late nineties, has devoted himself to the perfection of sushi for over seven decades. The counter seats just ten guests, and the meal — a procession of 20 or so nigiri pieces — is over in under an hour. Each fish is sourced from the same trusted vendors Jiro has worked with for decades, and the rice is seasoned with a vinegar blend he keeps secret. This is sushi stripped of all pretension, elevated to pure art.',
      imageUrl: 'https://images.unsplash.com/photo-1617196034183-421b4040ed20?w=800',
      rating: 4.9,
      priceRange: '$$$$',
      category: restaurants,
      tags: JSON.stringify(['sushi', 'omakase', 'tokyo', 'michelin star', 'japanese']),
      featured: false,
    },
    {
      title: 'The French Laundry',
      slug: 'the-french-laundry',
      description: 'Thomas Keller\'s three-Michelin-star destination in Napa Valley, celebrated for its exquisite nine-course tasting menus.',
      longDescription: 'Nestled in the heart of Yountville in California\'s Napa Valley, The French Laundry is the pinnacle of American fine dining. Chef Thomas Keller\'s philosophy of small portions in a lengthy succession allows diners to experience an extraordinary range of flavors without excess. The menu changes daily, reflecting what is most pristine from local farms, purveyors, and the restaurant\'s own garden. The wine cellar is among the finest in the country, and the service is a masterclass in intuitive hospitality. The stone cottage setting adds a bucolic charm to an otherwise cerebral dining experience.',
      imageUrl: 'https://images.unsplash.com/photo-1424847651672-bf20a4b0982b?w=800',
      rating: 4.8,
      priceRange: '$$$$',
      category: restaurants,
      tags: JSON.stringify(['american', 'tasting menu', 'napa valley', 'michelin star', 'thomas keller']),
      featured: false,
    },
    {
      title: 'Osteria Francescana',
      slug: 'osteria-francescana',
      description: 'Massimo Bottura\'s three-star masterpiece in Modena, where Italian tradition is reinterpreted with avant-garde creativity.',
      longDescription: 'Osteria Francescana, situated in a 16th-century building in Modena, is the creative laboratory of Massimo Bottura, one of the most imaginative chefs of his generation. His dishes are informed by art, music, and history as much as by food culture. The famous "Five Ages of Parmigiano Reggiano" is a single ingredient explored at different temperatures, ages, and textures. "Oops! I Dropped the Lemon Tart" turned a kitchen accident into an iconic dessert. To dine here is to engage with food as intellectual and emotional experience.',
      imageUrl: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800',
      rating: 4.9,
      priceRange: '$$$$',
      category: restaurants,
      tags: JSON.stringify(['italian', 'avant-garde', 'modena', 'michelin star', 'massimo bottura']),
      featured: true,
    },
    {
      title: 'Asador Etxebarri',
      slug: 'asador-etxebarri',
      description: 'Victor Arguinzoniz\'s Basque grill temple where fire and smoke elevate the finest ingredients to transcendent heights.',
      longDescription: 'Hidden in the hills of the Basque Country in a small village called Axpe, Asador Etxebarri is one of the world\'s most singular dining experiences. Chef Victor Arguinzoniz has spent decades mastering the art of the grill, designing custom equipment to cook over embers of different woods — oak, vine, cherry — chosen specifically for each ingredient. The buffalo milk curd with caviar, the freshly-made chorizo, the txuleta beef — each is perfected through fire. The rustic stone building, surrounded by mountains and meadows, adds to the feeling that you have discovered something secret and precious.',
      imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800',
      rating: 4.7,
      priceRange: '$$$',
      category: restaurants,
      tags: JSON.stringify(['basque', 'grill', 'spain', 'michelin star', 'fire cooking']),
      featured: false,
    },
  ]);

  // Seed High-End Audio
  await itemRepo.save([
    {
      title: 'Sennheiser HD 800 S',
      slug: 'sennheiser-hd-800-s',
      description: 'Reference open-back headphones with a 56mm ring radiator transducer, delivering an unmatched soundstage and resolution.',
      longDescription: 'The Sennheiser HD 800 S stands as one of the most technically accomplished headphones ever produced. The 56mm ring radiator transducer — borrowed from loudspeaker design — moves in a single plane, eliminating the membrane breakup modes that plague conventional drivers. The result is a frequency response that extends to 51kHz with extraordinary linearity in the audible range. The soundstage is breathtakingly wide — wider than many loudspeaker setups — and imaging is precise with exceptional depth. A rear-mounted absorber addresses a resonance that affected the original HD 800, resulting in a warmer, more musical presentation. These are the headphones that reveal everything your recordings contain.',
      imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800',
      rating: 4.8,
      priceRange: '$$$',
      category: audio,
      tags: JSON.stringify(['headphones', 'open-back', 'reference', 'sennheiser', 'audiophile']),
      featured: true,
    },
    {
      title: 'Chord Dave DAC',
      slug: 'chord-dave-dac',
      description: 'Rob Watts\' magnum opus: a desktop DAC/headphone amplifier with 164,000-tap FPGA filter, setting new standards for digital audio.',
      longDescription: 'The Chord Dave (Digital to Analogue Veritas in Extremis) represents the culmination of designer Rob Watts\' decades of research into digital filter theory and noise shaping. At its heart is a Xilinx FPGA running a 164,000-tap WTA filter — orders of magnitude more complex than conventional digital filters. This extraordinary tap length reconstructs the precise timing of the original audio waveform with vanishing errors. The noise shaping circuit operates at a modulation frequency of 104,448kHz. Dave is also a world-class headphone amplifier, capable of driving the most demanding loads with complete control. The aluminium chassis, illuminated fascia, and ring-shaped controls give it a sculptural presence on any desk.',
      imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
      rating: 4.9,
      priceRange: '$$$$',
      category: audio,
      tags: JSON.stringify(['DAC', 'headphone amplifier', 'FPGA', 'chord', 'desktop']),
      featured: true,
    },
    {
      title: 'Wilson Audio Alexia V',
      slug: 'wilson-audio-alexia-v',
      description: 'Flagship floorstanding loudspeaker from Wilson Audio, combining aerospace-grade cabinet materials with exceptional driver technology.',
      longDescription: 'The Wilson Audio Alexia V is the latest iteration of Wilson\'s celebrated Alexia line, refined over years of acoustic research conducted at the company\'s Utah facility. The cabinet is constructed from Wilson\'s proprietary S-Material and X-Material composites — developed for their optimal combination of mass, resonance damping, and stiffness. The adjustable module system allows the tweeter and midrange enclosures to be positioned for optimal time alignment in any room, a signature Wilson design principle. The bass drivers are titanium-domed, and the crossover components are point-to-point wired with Wilson\'s own Transparent Audio cable. The result is a speaker of staggering dynamic authority, resolution, and tonal richness.',
      imageUrl: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800',
      rating: 4.8,
      priceRange: '$$$$',
      category: audio,
      tags: JSON.stringify(['speakers', 'floorstanding', 'wilson audio', 'high-end', 'audiophile']),
      featured: false,
    },
    {
      title: 'Pass Labs XA60.8 Monoblocks',
      slug: 'pass-labs-xa60-8-monoblocks',
      description: 'Pure Class A monoblock amplifiers from Nelson Pass, delivering 60 watts of effortlessly refined power with zero crossover distortion.',
      longDescription: 'Nelson Pass is a legend in the audiophile world, and the XA60.8 monoblocks represent the refinement of his pure Class A amplifier design philosophy. Operating entirely in Class A means the output devices never switch off, eliminating the crossover distortion that mars Class AB amplifiers. Each monoblock delivers 60 watts into 8 ohms in Class A — sufficient for most high-efficiency loudspeakers — with the ability to double output for lower impedance loads. The circuit topology is elegant in its simplicity: single-ended JFET input, MOSFET output, with no global feedback. The massive heatsinks that flank the chassis are functional artworks. These amplifiers run warm to the touch and reward a patient listener with music of extraordinary intimacy and resolution.',
      imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
      rating: 4.7,
      priceRange: '$$$$',
      category: audio,
      tags: JSON.stringify(['amplifier', 'class A', 'monoblock', 'pass labs', 'solid state']),
      featured: false,
    },
    {
      title: 'Focal Utopia (2022)',
      slug: 'focal-utopia-2022',
      description: 'Focal\'s summit headphone featuring a pure beryllium M-shape driver, delivering reference transparency with a musical French character.',
      longDescription: 'The Focal Utopia 2022 revision represents French audio artistry at its finest. The defining technology is the pure beryllium M-shape dome driver — beryllium being the stiffest diaphragm material available for audio use, with a rigidity-to-mass ratio far exceeding titanium or aluminum. This results in a transducer that follows the audio signal with vanishing dynamic distortion. The 2022 update brings a redesigned yoke in carbon fiber with an improved headband that distributes the 490g weight with surprising comfort. The soundstage, resolution, and tonal accuracy set a benchmark. The French leather headband and open carbon fiber grilles add a visual elegance befitting the price.',
      imageUrl: 'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=800',
      rating: 4.9,
      priceRange: '$$$$',
      category: audio,
      tags: JSON.stringify(['headphones', 'open-back', 'beryllium', 'focal', 'reference']),
      featured: true,
    },
    {
      title: 'Naim ND 555 Streamer',
      slug: 'naim-nd-555',
      description: 'Naim\'s reference network player, offering state-of-the-art streaming performance with a legendary analogue output stage.',
      longDescription: 'The Naim ND 555 is the British manufacturer\'s statement network streamer, representing the pinnacle of over a decade\'s experience in digital playback. It pairs a sophisticated streaming engine — capable of rendering hi-res PCM and DSD files from network, USB, and internet radio sources — with a world-class analogue output stage descended from the legendary CD 555. The power supply topology isolates the digital and analogue domains on separate boards, and the unit is designed from the outset to accept Naim\'s outboard 555 PS DR power supply for further performance gains. The sonic character is quintessentially Naim: musical, rhythmically engaging, and deeply immersive.',
      imageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800',
      rating: 4.7,
      priceRange: '$$$$',
      category: audio,
      tags: JSON.stringify(['streamer', 'network player', 'naim', 'hi-res', 'digital']),
      featured: false,
    },
  ]);

  // Seed Luxury Watches
  await itemRepo.save([
    {
      title: 'Patek Philippe Nautilus 5711',
      slug: 'patek-philippe-nautilus-5711',
      description: 'The iconic Gerald Genta-designed sports watch that defined a category — now discontinued and more coveted than ever.',
      longDescription: 'The Patek Philippe Nautilus 5711 is arguably the most desired watch of the modern era. Designed by the legendary Gerald Genta in 1976, the integrated stainless steel bracelet and case were revolutionary for a fine watch manufacturer. The 5711 variant, produced from 2006 to 2021, housed Calibre 324 S C — a self-winding movement with a date display, glucydur balance, and Gyromax regulation. The matte blue dial with horizontal embossed pattern and applied Patek logo has become iconic. When Patek Philippe announced the discontinuation of the 5711, waiting lists that stretched years became moot — the secondary market immediately reflected its true cultural status. This is more than a watch; it is a sociological artifact.',
      imageUrl: 'https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=800',
      rating: 4.9,
      priceRange: '$$$$',
      category: watches,
      tags: JSON.stringify(['patek philippe', 'nautilus', 'sports watch', 'steel', 'gerald genta']),
      featured: true,
    },
    {
      title: 'A. Lange & Söhne Zeitwerk',
      slug: 'a-lange-sohne-zeitwerk',
      description: 'The most radical mechanical digital watch ever made, jumping the hours and minutes simultaneously with a single spring.',
      longDescription: 'The A. Lange & Söhne Zeitwerk is a mechanical tour de force. While digital displays in watches are commonplace in quartz timepieces, creating a mechanically jumping digital display of sufficient precision and power is an extraordinary horological challenge. The Zeitwerk solves it with an outsize mainspring, a precisely engineered constant-force mechanism that delivers equal energy to the escapement regardless of mainspring tension, and a jumping mechanism that advances both hour and minute numerals simultaneously at the top of each hour. The white gold case and argenté dial frame the jumping numerals against an architecture of brass bridges and levers visible through the exhibition caseback. This is mechanical watchmaking as intellectual achievement.',
      imageUrl: 'https://images.unsplash.com/photo-1548171915-e79a380a2a4b?w=800',
      rating: 4.8,
      priceRange: '$$$$',
      category: watches,
      tags: JSON.stringify(['a. lange & söhne', 'german', 'jumping hours', 'digital', 'complication']),
      featured: false,
    },
    {
      title: 'Rolex Daytona Ref. 116500LN',
      slug: 'rolex-daytona-116500ln',
      description: 'The definitive chronograph: ceramic bezel, column wheel, vertical clutch, and the legendary Daytona name on an in-house Calibre 4130.',
      longDescription: 'The Rolex Cosmograph Daytona has transcended its origins as a tool watch for racing drivers to become one of the defining watches of the 20th and 21st centuries. Reference 116500LN, introduced in 2016, brought a ceramic Cerachrom bezel to the Daytona for the first time — solving the scratching issues of the aluminium predecessor — and paired it with the in-house Calibre 4130. This movement, notable for its column wheel and vertical clutch, achieves chronograph engagement without the hand jump of traditional lateral clutch designs. The case is Oyster steel in 40mm, and the black dial with contrasting counters remains the most requested configuration. Demand has always exceeded supply by a significant multiple.',
      imageUrl: 'https://images.unsplash.com/photo-1547996160-81dfa63595aa?w=800',
      rating: 4.8,
      priceRange: '$$$',
      category: watches,
      tags: JSON.stringify(['rolex', 'daytona', 'chronograph', 'ceramic', 'sports watch']),
      featured: true,
    },
    {
      title: 'F.P. Journe Octa Reserve de Marche',
      slug: 'fp-journe-octa-reserve-de-marche',
      description: 'François-Paul Journe\'s iconic automatic with a 120-hour power reserve indicator, housed in rose gold with a brass movement.',
      longDescription: 'François-Paul Journe is the watchmaker\'s watchmaker — an independent horologist who does everything his own way, including making his own movements entirely in-house in Geneva. The Octa Reserve de Marche houses the celebrated Calibre 1300.3, an automatic movement with a 120-hour (five-day) power reserve displayed on a fan-shaped indicator at 12 o\'clock. The movement plate and bridges are made of brass, which Journe believes sounds more musical when the watch is wound and provides better lubricant retention over time. The rose gold case is 40mm and the signature grey dial, characteristic of F.P. Journe\'s natural patina aging, makes this instantly recognizable to those who know. These watches are made in very small numbers and appreciate significantly.',
      imageUrl: 'https://images.unsplash.com/photo-1526045431048-f857369baa09?w=800',
      rating: 4.9,
      priceRange: '$$$$',
      category: watches,
      tags: JSON.stringify(['f.p. journe', 'independent', 'power reserve', 'automatic', 'rose gold']),
      featured: false,
    },
    {
      title: 'IWC Portugieser Perpetual Calendar',
      slug: 'iwc-portugieser-perpetual-calendar',
      description: 'IWC\'s 44.2mm perpetual calendar with moon phase, day, date, month, and year displays, powered by the legendary 52610 calibre.',
      longDescription: 'The IWC Portugieser Perpetual Calendar is a grand complication housed in a case of restrained elegance. The Calibre 52610 that powers it contains a perpetual calendar mechanism that accounts for months of different lengths and leap years without requiring manual correction until 2100. The display is a model of clarity — the large white dial with blued steel hands presents the day, date, month, four-digit year, and moon phase across an uncluttered layout. The 44.2mm stainless steel case houses a movement of exceptional beauty, visible through the exhibition caseback. IWC\'s perpetual calendar mechanism is among the most technically praised in horology for its clever construction and ease of setting.',
      imageUrl: 'https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?w=800',
      rating: 4.7,
      priceRange: '$$$',
      category: watches,
      tags: JSON.stringify(['iwc', 'perpetual calendar', 'moon phase', 'complication', 'portuguese']),
      featured: false,
    },
    {
      title: 'Vacheron Constantin Overseas Dual Time',
      slug: 'vacheron-constantin-overseas-dual-time',
      description: 'The world traveller\'s watch par excellence: dual time zone, day/night indicator, and date in a sporty yet refined 41mm case.',
      longDescription: 'The Vacheron Constantin Overseas Dual Time represents the rare synthesis of tool-watch utility and haute horlogerie refinement. The Calibre 5110 DT movement displays two time zones simultaneously, with a clear day/night indicator for each to prevent calling contacts at 3am. The date is displayed centrally. The 41mm stainless steel case features the distinctive Overseas crown and integrated bracelet — one of the most comfortable integrated bracelets in the industry — and the dial architecture with its cross-hatch pattern is immediately recognizable. The watch comes with three interchangeable straps (rubber, leather, and bracelet) held by a clever quick-change system. Vacheron has been making watches since 1755 — the oldest continuously operating watch manufacturer in history.',
      imageUrl: 'https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=800',
      rating: 4.7,
      priceRange: '$$$$',
      category: watches,
      tags: JSON.stringify(['vacheron constantin', 'dual time', 'sports', 'travel', 'overseas']),
      featured: true,
    },
  ]);

  // Seed Curated Tech
  await itemRepo.save([
    {
      title: 'Apple MacBook Pro 16" M3 Max',
      slug: 'macbook-pro-16-m3-max',
      description: 'Apple\'s most powerful laptop, with the M3 Max chip delivering workstation-class performance in a remarkably thin aluminum chassis.',
      longDescription: 'The MacBook Pro 16" with M3 Max represents the current apex of laptop computing. The M3 Max chip, built on TSMC\'s 3nm process, contains up to 16 CPU cores and 40 GPU cores sharing a unified memory architecture of up to 128GB. The Liquid Retina XDR display achieves 1600 nits peak brightness, P3 wide color, and ProMotion adaptive refresh from 24Hz to 120Hz. The battery life — routinely exceeding 15 hours in professional use — is a particular achievement at this performance level. The MagSafe charging, full-size SD card reader, and HDMI port restore the connectivity professionals require. The speaker system, with its six speakers and spatial audio, is the finest ever fitted to a laptop.',
      imageUrl: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800',
      rating: 4.9,
      priceRange: '$$$',
      category: tech,
      tags: JSON.stringify(['apple', 'laptop', 'M3 Max', 'professional', 'macOS']),
      featured: true,
    },
    {
      title: 'Sony Alpha 1',
      slug: 'sony-alpha-1',
      description: 'Sony\'s flagship mirrorless camera: 50.1MP stacked CMOS sensor, 30fps continuous shooting, 8K video, and 759-point AF system.',
      longDescription: 'The Sony Alpha 1 is, simply, the most capable camera ever made for most applications. The 50.1-megapixel stacked Exmor RS CMOS sensor achieves 30 frames per second continuous shooting with full autofocus — a combination that was technically unimaginable five years ago. The autofocus system covers 759 phase-detection points across 92% of the frame and tracks subjects with an accuracy that renders focus anxiety largely obsolete for wildlife, sports, and event work. 8K30 video and 4K120 are captured in 10-bit XAVC HS with S-Log profiles. The blackout-free electronic viewfinder operates at 240fps. This camera merges the resolving power of a studio landscape camera with the speed of a sports tool and the video capability of a cinema camera.',
      imageUrl: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800',
      rating: 4.8,
      priceRange: '$$$',
      category: tech,
      tags: JSON.stringify(['sony', 'camera', 'mirrorless', 'photography', 'video']),
      featured: false,
    },
    {
      title: 'Leica M11',
      slug: 'leica-m11',
      description: 'The rangefinder reimagined: 60MP BSI CMOS sensor, triple-resolution capture, and the timeless M-mount system in a refined brass body.',
      longDescription: 'The Leica M11 is the latest evolution of the most storied camera system in photography. The rangefinder form factor, essentially unchanged since the M3 of 1954, now houses a 60-megapixel BSI CMOS sensor without a low-pass filter, paired with Leica\'s Triple Resolution Technology that captures simultaneously at 60MP, 36MP, and 18MP. The brass top plate (in black-painted or silver chrome versions) is machined to tolerances that reflect the company\'s watchmaking roots. The M-mount lens ecosystem encompasses some of the finest optics ever designed for photography. Shooting with an M forces a deliberateness and intentionality that digital workflows often discourage. The results, especially with M-system glass, possess a character and three-dimensionality that defies technical explanation.',
      imageUrl: 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800',
      rating: 4.7,
      priceRange: '$$$$',
      category: tech,
      tags: JSON.stringify(['leica', 'camera', 'rangefinder', 'photography', 'M-system']),
      featured: true,
    },
    {
      title: 'Garmin Fenix 7X Pro Solar',
      slug: 'garmin-fenix-7x-pro-solar',
      description: 'The ultimate multisport GPS watch: solar charging, topographic maps, military-grade durability, and comprehensive health monitoring.',
      longDescription: 'The Garmin Fenix 7X Pro Solar is the definitive tool watch for the serious outdoor enthusiast. The titanium bezel and Corning Gorilla Glass DX+ lens are engineered to survive the environments where this watch is deployed. Solar charging via Power Glass technology extends battery life beyond what is strictly necessary — the standard GPS mode already offers 89 hours — turning this into a watch you can forget to charge for weeks. The built-in topographic maps cover 2000+ courses worldwide. Multi-band GPS acquires satellites faster and more accurately than conventional single-band designs. Health monitoring includes wrist-based pulse oximetry, sleep stages, HRV status, and recovery advisor. This is precision instrumentation with a luxury finish.',
      imageUrl: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800',
      rating: 4.7,
      priceRange: '$$$',
      category: tech,
      tags: JSON.stringify(['garmin', 'smartwatch', 'GPS', 'outdoor', 'sports']),
      featured: false,
    },
    {
      title: 'Sonos Era 300',
      slug: 'sonos-era-300',
      description: 'Sonos\' spatial audio speaker with six drivers arranged for Dolby Atmos music, offering room-filling three-dimensional sound.',
      longDescription: 'The Sonos Era 300 marks a significant evolution in home wireless audio. Designed from the ground up for Dolby Atmos spatial audio content, it houses six drivers — four tweeters (firing forward, side, and upward), two woofers, and a high-excursion angled woofer — arranged to create a three-dimensional sound field that extends above and to the sides of the listener. Streaming Dolby Atmos tracks from Apple Music or Amazon Music HD, the Era 300 creates an enveloping spatial experience that conventional stereo systems cannot replicate. The acoustic tuning via Sonos TruePlay, which uses the room\'s dimensions to optimize the EQ, is among the best automatic room correction systems at this price. The matte finish and sculptural form are the most design-forward of any Sonos product.',
      imageUrl: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800',
      rating: 4.6,
      priceRange: '$$',
      category: tech,
      tags: JSON.stringify(['sonos', 'speaker', 'spatial audio', 'dolby atmos', 'wireless']),
      featured: false,
    },
    {
      title: 'reMarkable 2',
      slug: 'remarkable-2',
      description: 'The world\'s thinnest tablet at 4.7mm, designed exclusively for writing and reading with a paper-like display and zero distractions.',
      longDescription: 'The reMarkable 2 is a single-purpose device in an era of distraction — and that is its greatest strength. At 4.7mm thin, it is the thinnest tablet ever produced, and the CANVAS display — a second-generation E Ink screen with a textured glass overlay — provides a writing experience that is closer to paper than any other digital surface. There are no notifications, no social media apps, no web browser. Only a remarkably capable notebook and PDF reader. The handwriting recognition, which converts your notes to typed text, is among the best available. For academics, writers, architects, and executives who need a focused thinking tool rather than another screen, the reMarkable 2 is unmatched.',
      imageUrl: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800',
      rating: 4.5,
      priceRange: '$$',
      category: tech,
      tags: JSON.stringify(['remarkable', 'tablet', 'e-ink', 'writing', 'productivity']),
      featured: false,
    },
  ]);

  // Seed Fine Spirits
  await itemRepo.save([
    {
      title: 'Yamazaki 18 Year Single Malt',
      slug: 'yamazaki-18-year',
      description: 'Suntory\'s landmark Japanese single malt, showcasing the extraordinary range of Japan\'s oldest whisky distillery across 18 years of maturation.',
      longDescription: 'The Yamazaki 18 Year is the whisky that brought Japanese single malt to the world\'s attention, winning the World\'s Best Single Malt at the World Whiskies Awards in 2015. Distilled at the Yamazaki distillery outside Kyoto — Japan\'s oldest operating whisky distillery, established by Shinjiro Torii in 1923 — and matured for a minimum of 18 years across a variety of cask types including American white oak, Spanish oak, and Japanese Mizunara oak. The result is a spirit of exceptional complexity: dried fruits, leather, candied orange, chocolate, and the distinctive Mizunara incense note that is uniquely Japanese. The presentation, in a traditional Japanese apothecary bottle, is as considered as the liquid within.',
      imageUrl: 'https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=800',
      rating: 4.9,
      priceRange: '$$$',
      category: spirits,
      tags: JSON.stringify(['japanese whisky', 'single malt', 'suntory', 'yamazaki', '18 year']),
      featured: true,
    },
    {
      title: 'Pappy Van Winkle 23 Year',
      slug: 'pappy-van-winkle-23-year',
      description: 'The most mythologized bourbon in America: 23 years in charred oak barrels, wheated mashbill, and production so limited it borders on legend.',
      longDescription: 'Pappy Van Winkle 23 Year Family Reserve is less a bourbon and more a cultural artifact. Produced by Buffalo Trace Distillery under the Van Winkle family label, its production is so limited that the annual release — each November — generates news coverage, lottery systems, and secondary market prices that can exceed ten times the suggested retail price. The wheated mashbill (replacing rye with wheat as the secondary grain) contributes a softness and sweetness that tempers the intensity of 23 years in new charred American oak. The color is a deep mahogany, and the nose presents antique leather, dried cherry, and a caramel richness that is almost overwhelming. This is bourbon as a once-in-a-lifetime experience.',
      imageUrl: 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=800',
      rating: 4.9,
      priceRange: '$$$$',
      category: spirits,
      tags: JSON.stringify(['bourbon', 'american whiskey', 'pappy van winkle', 'buffalo trace', '23 year']),
      featured: true,
    },
    {
      title: 'Château Margaux 2015',
      slug: 'chateau-margaux-2015',
      description: 'The 2015 vintage of this Premier Grand Cru Classé from Margaux is considered a modern benchmark: opulent, structured, and immortal.',
      longDescription: 'Château Margaux 2015 is, by many critical assessments, one of the greatest vintages produced in the estate\'s long history. Winemaker Paul Pontallier (in his final vintage before his death in 2016) supervised a harvest of near-perfect conditions — warm, dry, with minerally early rain that concentrated the berries beautifully. The wine\'s blend of approximately 88% Cabernet Sauvignon, with Merlot and Petit Verdot, is aged for 18 months in new French oak. In youth, the wine presents extraordinary depth of violet, cassis, cedar, and graphite. The structure of tannins and acid suggests a development curve stretching decades. Robert Parker gave it 100 points. It is, by any measure, perfection in a bottle.',
      imageUrl: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800',
      rating: 5.0,
      priceRange: '$$$$',
      category: spirits,
      tags: JSON.stringify(['bordeaux', 'cabernet sauvignon', 'château margaux', 'wine', 'premier cru']),
      featured: false,
    },
    {
      title: 'Ardbeg Uigeadail',
      slug: 'ardbeg-uigeadail',
      description: 'Named after the loch that supplies Ardbeg\'s water, this NAS expression combines sherry cask richness with Islay\'s most medicinal peat smoke.',
      longDescription: 'Ardbeg Uigeadail (pronounced "oog-a-dal") is a masterclass in balance between apparent opposites. The distillery on the south coast of Islay produces the most heavily peated malt whisky in regular production — phenol levels around 55 parts per million — yet the Uigeadail marries this medicinal, briny, bonfire peat intensity with the dried fruit richness and Christmas cake sweetness of sherry-seasoned casks. The combination is extraordinary: smoked salmon and stewed plum; ash and dark chocolate; oyster brine and espresso. Named the World\'s Best Single Malt by Whisky Magazine in 2009. At its retail price, it represents the greatest value in whisky.',
      imageUrl: 'https://images.unsplash.com/photo-1518099074172-2e47ee6cfdc0?w=800',
      rating: 4.8,
      priceRange: '$$',
      category: spirits,
      tags: JSON.stringify(['scotch whisky', 'islay', 'peated', 'sherry cask', 'ardbeg']),
      featured: false,
    },
    {
      title: 'The Tommy\'s Margarita',
      slug: 'tommys-margarita',
      description: 'Julio Bermejo\'s 1988 invention at Tommy\'s Mexican Restaurant in San Francisco: agave nectar instead of triple sec, showcasing tequila\'s true character.',
      longDescription: 'The Tommy\'s Margarita is the most important craft cocktail of the modern era — a simple adjustment to the classic Margarita formula that has changed how the world thinks about tequila. Julio Bermejo, working at his family\'s San Francisco restaurant in 1988, replaced triple sec with agave nectar, arguing that the orange liqueur obscures tequila\'s natural agave character. He was right. The recipe: 2oz 100% blue agave blanco or reposado tequila (Bermejo recommends Siete Leguas), 1oz fresh lime juice, ½oz agave nectar (diluted 1:1 with water). The result is a drink of remarkable transparency — the quality of the tequila is front and center, which means only the finest will do. Use Tapatio, Siete Leguas, or El Tesoro.',
      imageUrl: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=800',
      rating: 4.7,
      priceRange: '$',
      category: spirits,
      tags: JSON.stringify(['cocktail', 'tequila', 'margarita', 'agave', 'craft cocktail']),
      featured: false,
    },
    {
      title: 'Dom Pérignon 2013 Vintage',
      slug: 'dom-perignon-2013',
      description: 'The prestige cuvée from Moët & Chandon, declared only in exceptional years: 2013 brought precision, tension, and remarkable aging potential.',
      longDescription: 'Dom Pérignon is produced only in vintages that Chef de Cave Richard Geoffroy and his successor Vincent Chaperon deem worthy of the name — approximately seven out of every ten years. The 2013 vintage, characterized by a challenging summer followed by an exceptional September and October harvest, produced a wine of extraordinary tension and precision. The cuvée, a blend of Chardonnay and Pinot Noir from the finest Montagne de Reims and Côte des Blancs vineyards, spends a minimum of seven years on its lees before disgorgement. The 2013 presents white flowers, citrus pith, toasted brioche, and a mineral salinity that gives it tremendous aging potential. This is Champagne elevated to the status of fine wine.',
      imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
      rating: 4.8,
      priceRange: '$$$',
      category: spirits,
      tags: JSON.stringify(['champagne', 'sparkling wine', 'dom perignon', 'prestige cuvée', 'vintage']),
      featured: true,
    },
  ]);
}
